### ISSUE TITLE
Pull of Concrete Sections in German

### ISSUE THREAD

**Issue by staintono** [BHoM/RFEM_Toolkit#140]
#### Description:
With RFEM set to German concrete sections arent pulled correctly. As RFEM has a German user base this poses an issue.

In German the section name is "Rechteck 300/300" rather than "Rectangle 300/300" which is currently recognised. 

#### Steps to reproduce:
Open RFEM in German, create a bar with a concrete section. Pull into GH using the RFEM adapter to produce error.

#### Expected behaviour:
Concrete section to be pulled into GH.

#### Test file(s):
As this is dependant on the users RFEM language, no test file can be provided. To reproduce follow the steps above.

**Comment by MartinHenriksen** [comment]
this was closed in PR #140
