### ISSUE TITLE
Loads, Load Cases

### ISSUE THREAD

**Issue by jholik** [BHoM/RFEM_Toolkit#38]
Can we add creating and managing of those in RFEM Adapter:

- Loads
- Load Cases
- Load Combinations / Result Combinations

**Comment by MartinHenriksen** [comment]
removed load combinations from description and created a separate issue for this: #123

**Comment by MartinHenriksen** [comment]
@njsmithies you have re-opened a closed issue. If there is a bug or missing feature related to this issue please open a new issue with the specifics.
Closing this again.
