### ISSUE TITLE
Pull non-library SectionProperty

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/RFEM_Toolkit#95]
#### Description:

When pulling a `SectonProperty` from RFEM it defaults to an `ExplicitSection` if the section name cannot be found in the library. 

Can supported be added for the various `ShapeProfiles` in the BHoM?

**Comment by Arne-Martensen** [comment]
@peterjamesnugent would it be possible to provide a simple script to illustrate the issue? I know it has been a while sice the issue were raised but would really help me to understand what exactly the problems was/is :),

**Comment by peterjamesnugent** [comment]
Hi @Arne-Martensen, I no longer have a licence for RFEM and I am not sure if this functionality has not been updated.

1. Create a `SteelBoxSection`
2. Push to RFEM
3. Pull `SectionProperty` from RFEM
4. The pulled section will be an `ExplicitSection` when it should really come back as a `SteelBoxSection`

My initial issue raised to address this - if you look at all the other structural adapters they will use dynamic casts to solve this.
